// Generated by CoffeeScript 1.3.3
(function() {
  var current_game, match, new_game, reposition, score, score_limit, send_results, server_url;

  server_url = "";

  score_limit = 5;

  match = [];

  current_game = {};

  new_game = function(players) {
    return current_game = {
      goals: [],
      arrangement: players,
      scores: [0, 0]
    };
  };

  score = function(player) {
    var goal, scoring_team;
    goal = {
      time: new Date(),
      scorer: player,
      arrangement: current_game.arrangement
    };
    current_game.goals.push(goal);
    scoring_team = (current_game.arrangement[0].indexOf(player) > -1 ? 0 : 1);
    current_game.scores[scoring_team]++;
    if (current_game.scores[0] === score_limit || current_game.scores[1] === score_limit) {
      match.push(current_game);
      return new_game(current_game.arrangement);
    }
  };

  reposition = function(new_arrangement) {
    return current_game.arrangement = new_arrangement;
  };

  send_results = function() {
    return $.post(server_url, match);
  };

}).call(this);
