// Generated by CoffeeScript 1.3.3
(function() {

  this.Game = {
    server_url: "",
    score_limit: 5,
    options: {
      enablePrivilege: false,
      consumerKey: "08158d5fadd4eaf3f1da",
      consumerSecret: "ac6d87540c0ff4d36d73464ee610f6c2f91c7cc5"
    },
    oauth: null,
    match: [],
    current_game: {},
    new_game: function(players) {
      return this.current_game = {
        goals: [],
        arrangement: players,
        scores: [0, 0]
      };
    },
    score: function(player) {
      var goal, scoring_team;
      goal = {
        time: new Date(),
        scorer: player,
        arrangement: this.current_game.arrangement
      };
      this.current_game.goals.push(goal);
      scoring_team = (this.current_game.arrangement[0].indexOf(player) > -1 ? 0 : 1);
      this.current_game.scores[scoring_team]++;
      if (this.current_game.scores[0] === this.score_limit || this.current_game.scores[1] === this.score_limit) {
        this.match.push(this.current_game);
        return this.new_game(this.current_game.arrangement);
      }
    },
    reposition: function(new_arrangement) {
      return this.current_game.arrangement = new_arrangement;
    },
    send_results: function() {
      return $.post(this.server_url, this.match);
    },
    get_oauth: function() {
      if (!this.oauth) {
        this.oauth = OAuth(this.options);
      }
      return this.oauth;
    },
    get_github_profile: function(player, callback) {
      return this.get_oauth().get("https://api.github.com/users/" + player, callback);
    }
  };

}).call(this);
