// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  this.GameView = {
    initialize: function() {
      $("#box").sortable({
        change: function() {
          return GameController.reposition(GameView.get_arrangement());
        }
      });
      return $("#box").disableSelection();
    },
    get_arrangement: function() {
      var players;
      players = $('.player .name').map(function(i, elt) {
        return elt.innerText;
      });
      return [[players[1], players[0]], [players[2], players[3]]];
    }
  };

  this.GameController = {
    server_url: "",
    score_limit: 5,
    match: [],
    current_game: {},
    new_game: function(players) {
      return this.current_game = {
        goals: [],
        arrangement: players,
        scores: [0, 0]
      };
    },
    score: function(player) {
      var goal, scoring_team;
      goal = {
        time: new Date(),
        scorer: player,
        arrangement: this.current_game.arrangement
      };
      this.current_game.goals.push(goal);
      scoring_team = (__indexOf.call(this.current_game.arrangement[0], player) >= 0 ? 0 : 1);
      this.current_game.scores[scoring_team]++;
      if (this.current_game.scores[0] === this.score_limit || this.current_game.scores[1] === this.score_limit) {
        this.match.push(this.current_game);
        return this.new_game(this.current_game.arrangement);
      }
    },
    undo_score: function() {
      return this.current_game.goals.pop;
    },
    reposition: function(new_arrangement) {
      return this.current_game.arrangement = new_arrangement;
    },
    send_results: function() {
      return $.post(this.server_url, this.match);
    }
  };

}).call(this);
